specVersion: 0.0.2
description: Subgraph for the Ampleforth protocol contracts on ethereum
repository: https://github.com/ampleforth/ampleforth-subgraph
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: CPIOracle
    network: kovan
    source:
      abi: OracleABI
      address: '0xCedc17B394051d0E222797588f3e5ECe5023FB4A'
      startBlock: 11666618
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      abis:
        - name: OracleABI
          file: ../sdk/src/abis/MedianOracle.json
      entities:
        - MedianOracle
      callHandlers:
        - function: setReportDelaySec(uint256)
          handler: handleHyperParamUpdate
        - function: setReportExpirationTimeSec(uint256)
          handler: handleHyperParamUpdate
        - function: setMinimumProviders(uint256)
          handler: handleHyperParamUpdate
        - function: pushReport(uint256)
          handler: handlePushReport
        - function: purgeReports()
          handler: handlePurgeReports
      eventHandlers:
        - event: ProviderAdded(address)
          handler: handleAddProvider
        - event: ProviderRemoved(address)
          handler: handleRemoveProvider
      file: ./src/datasources/oracle.ts
      language: wasm/assemblyscript

  - kind: ethereum/contract
    name: MarketOracle
    network: kovan
    source:
      abi: OracleABI
      address: '0xFC344AF21d647f4244B5F098203A178BF26c51Dc'
      startBlock: 11666602
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      abis:
        - name: OracleABI
          file: ../sdk/src/abis/MedianOracle.json
      entities:
        - MedianOracle
      callHandlers:
        - function: setReportDelaySec(uint256)
          handler: handleHyperParamUpdate
        - function: setReportExpirationTimeSec(uint256)
          handler: handleHyperParamUpdate
        - function: setMinimumProviders(uint256)
          handler: handleHyperParamUpdate
        - function: pushReport(uint256)
          handler: handlePushReport
        - function: purgeReports()
          handler: handlePurgeReports
      eventHandlers:
        - event: ProviderAdded(address)
          handler: handleAddProvider
        - event: ProviderRemoved(address)
          handler: handleRemoveProvider
      file: ./src/datasources/oracle.ts
      language: wasm/assemblyscript

  - kind: ethereum/contract
    name: Policy
    network: kovan
    source:
      abi: PolicyABI
      address: '0xBB4617d26E704Ac0568E1cbf5232990a8b7846A4'
      startBlock: 11666553
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      abis:
        - name: PolicyABI
          file: ../sdk/src/abis/UFragmentsPolicy.json
      entities:
        - Policy
      callHandlers:
        - function: setDeviationThreshold(uint256)
          handler: handleHyperParamUpdate
        - function: setRebaseLag(uint256)
          handler: handleHyperParamUpdate
        - function: setRebaseTimingParameters(uint256,uint256,uint256)
          handler: handleHyperParamUpdate
      eventHandlers:
        - event: LogRebase(indexed uint256,uint256,uint256,int256,uint256)
          handler: handleRebase
      file: ./src/datasources/policy.ts
      language: wasm/assemblyscript

  - kind: ethereum/contract
    name: Token
    network: kovan
    source:
      abi: TokenABI
      address: '0x3E0437898a5667a4769B1Ca5A34aAB1ae7E81377'
      startBlock: 11666536
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      abis:
        - name: TokenABI
          file: ../sdk/src/abis/UFragments.json
      entities:
        - Token
      callHandlers:
        - function: setMonetaryPolicy(address)
          handler: handleHyperParamUpdate
        - function: transferFrom(address,address,uint256)
          handler: handleApprovalUpdateOnTransferFrom
        - function: transferAllFrom(address,address)
          handler: handleApprovalUpdateOnTransferAllFrom
      eventHandlers:
        - event: LogRebase(indexed uint256,uint256)
          handler: handleRebase
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Approval(indexed address,indexed address,uint256)
          handler: handleApproval
      file: ./src/datasources/token.ts
      language: wasm/assemblyscript
